// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqroxesqxyzyxzywkybc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcm94ZXNxeHl6eXh6eXdreWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjAwMTYsImV4cCI6MjA3MTc5NjAxNn0.IEQ1LPO-np1zprAsoQwiGqdl3C3AAUKvJbk070PC-rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});